stages:
  prepare:
    cmd: python src/prepare/prepare.py
    deps:
      - src/prepare/prepare.py
      - data/raw
    params:
      - params.yaml:
    outs:
      - data/clean
  
  # train:
  #   cmd: i
  #   deps:
  #   - data
  #   - src
  #   params:
  #   - params.yaml:
  #   outs:
  #   - models
  #   metrics:
  #   - metrics.json:
  #       cache: false
  #   plots:
  #   - plots:
  #       cache: false
